import { Injectable, signal, Signal } from '@angular/core';
import { IDdiEN } from '../../_models/interface/share-interfaces';

@Injectable({
  providedIn: 'root',
})
export class CountryCodesService {
  fireBaseddiData: Signal<IDdiEN[]> = signal([
    {
      code: '004',
      phone: '0093',
      iso: 'AF',
      iso3: 'AFG',
      name: 'Afghanistan',
      formalName: 'Islamic Republic of Afghanistan',
    },
    {
      code: '008',
      phone: '0355',
      iso: 'AL',
      iso3: 'ALB',
      name: 'Albania',
      formalName: 'Republic of Albania',
    },
    {
      code: '012',
      phone: '0213',
      iso: 'DZ',
      iso3: 'DZA',
      name: 'Algeria',
      formalName: "People's Democratic Republic of Algeria",
    },
    {
      code: '016',
      phone: '1684',
      iso: 'AS',
      iso3: 'ASM',
      name: 'American Samoa',
      formalName: 'Territory of American Samoa',
    },
    {
      code: '020',
      phone: '0376',
      iso: 'AD',
      iso3: 'AND',
      name: 'Andorra',
      formalName: 'Principality of Andorra',
    },
    {
      code: '024',
      phone: '0244',
      iso: 'AO',
      iso3: 'AGO',
      name: 'Angola',
      formalName: 'Republic of Angola',
    },
    {
      code: '660',
      phone: '1264',
      iso: 'AI',
      iso3: 'AIA',
      name: 'Anguilla',
      formalName: 'Anguilla',
    },
    {
      code: '010',
      phone: '0672',
      iso: 'AQ',
      iso3: 'ATA',
      name: 'Antarctica',
      formalName: 'Antarctica',
    },
    {
      code: '028',
      phone: '1268',
      iso: 'AG',
      iso3: 'ATG',
      name: 'Antigua and Barbuda',
      formalName: 'Antigua and Barbuda',
    },
    {
      code: '032',
      phone: '0054',
      iso: 'AR',
      iso3: 'ARG',
      name: 'Argentina',
      formalName: 'Argentine Republic',
    },
    {
      code: '051',
      phone: '0374',
      iso: 'AM',
      iso3: 'ARM',
      name: 'Armenia',
      formalName: 'Republic of Armenia',
    },
    {
      code: '533',
      phone: '0297',
      iso: 'AW',
      iso3: 'ABW',
      name: 'Aruba',
      formalName: 'Aruba',
    },
    {
      code: '036',
      phone: '0061',
      iso: 'AU',
      iso3: 'AUS',
      name: 'Australia',
      formalName: 'Commonwealth of Australia',
    },
    {
      code: '040',
      phone: '0043',
      iso: 'AT',
      iso3: 'AUT',
      name: 'Austria',
      formalName: 'Republic of Austria',
    },
    {
      code: '031',
      phone: '0994',
      iso: 'AZ',
      iso3: 'AZE',
      name: 'Azerbaijan',
      formalName: 'Republic of Azerbaijan',
    },
    {
      code: '044',
      phone: '1242',
      iso: 'BS',
      iso3: 'BHS',
      name: 'Bahamas',
      formalName: 'Commonwealth of the Bahamas',
    },
    {
      code: '048',
      phone: '0973',
      iso: 'BH',
      iso3: 'BHR',
      name: 'Bahrain',
      formalName: 'Kingdom of Bahrain',
    },
    {
      code: '050',
      phone: '0880',
      iso: 'BD',
      iso3: 'BGD',
      name: 'Bangladesh',
      formalName: "People's Republic of Bangladesh",
    },
    {
      code: '052',
      phone: '0246',
      iso: 'BB',
      iso3: 'BRB',
      name: 'Barbados',
      formalName: 'Barbados',
    },
    {
      code: '112',
      phone: '0375',
      iso: 'BY',
      iso3: 'BLR',
      name: 'Belarus',
      formalName: 'Republic of Belarus',
    },
    {
      code: '056',
      phone: '0032',
      iso: 'BE',
      iso3: 'BEL',
      name: 'Belgium',
      formalName: 'Kingdom of Belgium',
    },
    {
      code: '084',
      phone: '0501',
      iso: 'BZ',
      iso3: 'BLZ',
      name: 'Belize',
      formalName: 'Belize',
    },
    {
      code: '204',
      phone: '0229',
      iso: 'BJ',
      iso3: 'BEN',
      name: 'Benin',
      formalName: 'Republic of Benin',
    },
    {
      code: '060',
      phone: '1441',
      iso: 'BM',
      iso3: 'BMU',
      name: 'Bermuda',
      formalName: 'Bermuda',
    },
    {
      code: '064',
      phone: '0975',
      iso: 'BT',
      iso3: 'BTN',
      name: 'Bhutan',
      formalName: 'Kingdom of Bhutan',
    },
    {
      code: '068',
      phone: '0591',
      iso: 'BO',
      iso3: 'BOL',
      name: 'Bolivia',
      formalName: 'Plurinational State of Bolivia',
    },
    {
      code: '070',
      phone: '0387',
      iso: 'BA',
      iso3: 'BIH',
      name: 'Bosnia and Herzegovina',
      formalName: 'Bosnia and Herzegovina',
    },
    {
      code: '072',
      phone: '0267',
      iso: 'BW',
      iso3: 'BWA',
      name: 'Botswana',
      formalName: 'Republic of Botswana',
    },
    {
      code: '074',
      phone: '0047',
      iso: 'BV',
      iso3: 'BVT',
      name: 'Bouvet Island',
      formalName: 'Bouvet Island',
    },
    {
      code: '076',
      phone: '0055',
      iso: 'BR',
      iso3: 'BRA',
      name: 'Brazil',
      formalName: 'Federative Republic of Brazil',
    },
    {
      code: '086',
      phone: '0246',
      iso: 'IO',
      iso3: 'IOT',
      name: 'British Indian Ocean Territory',
      formalName: 'British Indian Ocean Territory',
    },
    {
      code: '096',
      phone: '0673',
      iso: 'BN',
      iso3: 'BRN',
      name: 'Brunei',
      formalName: 'State of Brunei Darussalam',
    },
    {
      code: '100',
      phone: '0359',
      iso: 'BG',
      iso3: 'BGR',
      name: 'Bulgaria',
      formalName: 'Republic of Bulgaria',
    },
    {
      code: '854',
      phone: '0226',
      iso: 'BF',
      iso3: 'BFA',
      name: 'Burkina Faso',
      formalName: 'Burkina Faso',
    },
    {
      code: '108',
      phone: '0257',
      iso: 'BI',
      iso3: 'BDI',
      name: 'Burundi',
      formalName: 'Republic of Burundi',
    },
    {
      code: '116',
      phone: '0855',
      iso: 'KH',
      iso3: 'KHM',
      name: 'Cambodia',
      formalName: 'Kingdom of Cambodia',
    },
    {
      code: '120',
      phone: '0237',
      iso: 'CM',
      iso3: 'CMR',
      name: 'Cameroon',
      formalName: 'Republic of Cameroon',
    },
    {
      code: '124',
      phone: '0001',
      iso: 'CA',
      iso3: 'CAN',
      name: 'Canada',
      formalName: 'Canada',
    },
    {
      code: '132',
      phone: '0238',
      iso: 'CV',
      iso3: 'CPV',
      name: 'Cape Verde',
      formalName: 'Republic of Cape Verde',
    },
    {
      code: '136',
      phone: '1345',
      iso: 'KY',
      iso3: 'CYM',
      name: 'Cayman Islands',
      formalName: 'Cayman Islands',
    },
    {
      code: '140',
      phone: '0236',
      iso: 'CF',
      iso3: 'CAF',
      name: 'Central African Republic',
      formalName: 'Central African Republic',
    },
    {
      code: '148',
      phone: '0235',
      iso: 'TD',
      iso3: 'TCD',
      name: 'Chad',
      formalName: 'Republic of Chad',
    },
    {
      code: '152',
      phone: '0056',
      iso: 'CL',
      iso3: 'CHL',
      name: 'Chile',
      formalName: 'Republic of Chile',
    },
    {
      code: '156',
      phone: '0086',
      iso: 'CN',
      iso3: 'CHN',
      name: 'China',
      formalName: "People's Republic of China",
    },
    {
      code: '162',
      phone: '0061',
      iso: 'CX',
      iso3: 'CXR',
      name: 'Christmas Island',
      formalName: 'Territory of Christmas Island',
    },
    {
      code: '166',
      phone: '0672',
      iso: 'CC',
      iso3: 'CCK',
      name: 'Cocos (Keeling) Islands',
      formalName: 'Territory of the Cocos (Keeling) Islands',
    },
    {
      code: '170',
      phone: '0057',
      iso: 'CO',
      iso3: 'COL',
      name: 'Colombia',
      formalName: 'Republic of Colombia',
    },
    {
      code: '174',
      phone: '0269',
      iso: 'KM',
      iso3: 'COM',
      name: 'Comoros',
      formalName: 'Union of the Comoros',
    },
    {
      code: '178',
      phone: '0242',
      iso: 'CG',
      iso3: 'COG',
      name: 'Congo',
      formalName: 'Republic of the Congo',
    },
    {
      code: '180',
      phone: '0242',
      iso: 'CD',
      iso3: 'COD',
      name: 'Congo (DR)',
      formalName: 'Democratic Republic of the Congo',
    },
    {
      code: '184',
      phone: '0682',
      iso: 'CK',
      iso3: 'COK',
      name: 'Cook Islands',
      formalName: 'Cook Islands',
    },
    {
      code: '188',
      phone: '0506',
      iso: 'CR',
      iso3: 'CRI',
      name: 'Costa Rica',
      formalName: 'Republic of Costa Rica',
    },
    {
      code: '384',
      phone: '0225',
      iso: 'CI',
      iso3: 'CIV',
      name: 'Ivory Coast',
      formalName: 'Republic of Ivory Coast',
    },
    {
      code: '191',
      phone: '0385',
      iso: 'HR',
      iso3: 'HRV',
      name: 'Croatia',
      formalName: 'Republic of Croatia',
    },
    {
      code: '192',
      phone: '0053',
      iso: 'CU',
      iso3: 'CUB',
      name: 'Cuba',
      formalName: 'Republic of Cuba',
    },
    {
      code: '196',
      phone: '0357',
      iso: 'CY',
      iso3: 'CYP',
      name: 'Cyprus',
      formalName: 'Republic of Cyprus',
    },
    {
      code: '203',
      phone: '0420',
      iso: 'CZ',
      iso3: 'CZE',
      name: 'Czech Republic',
      formalName: 'Czech Republic',
    },
    {
      code: '208',
      phone: '0045',
      iso: 'DK',
      iso3: 'DNK',
      name: 'Denmark',
      formalName: 'Kingdom of Denmark',
    },
    {
      code: '262',
      phone: '0253',
      iso: 'DJ',
      iso3: 'DJI',
      name: 'Djibouti',
      formalName: 'Republic of Djibouti',
    },
    {
      code: '212',
      phone: '1767',
      iso: 'DM',
      iso3: 'DMA',
      name: 'Dominica',
      formalName: 'Commonwealth of Dominica',
    },
    {
      code: '214',
      phone: '1809',
      iso: 'DO',
      iso3: 'DOM',
      name: 'Dominican Republic',
      formalName: 'Dominican Republic',
    },
    {
      code: '218',
      phone: '0593',
      iso: 'EC',
      iso3: 'ECU',
      name: 'Ecuador',
      formalName: 'Republic of Ecuador',
    },
    {
      code: '818',
      phone: '0020',
      iso: 'EG',
      iso3: 'EGY',
      name: 'Egypt',
      formalName: 'Arab Republic of Egypt',
    },
    {
      code: '222',
      phone: '0503',
      iso: 'SV',
      iso3: 'SLV',
      name: 'El Salvador',
      formalName: 'Republic of El Salvador',
    },
    {
      code: '226',
      phone: '0240',
      iso: 'GQ',
      iso3: 'GNQ',
      name: 'Equatorial Guinea',
      formalName: 'Republic of Equatorial Guinea',
    },
    {
      code: '070',
      phone: '0387',
      iso: 'BA',
      iso3: 'BIH',
      name: 'Bosnia and Herzegovina',
      formalName: 'Bosnia and Herzegovina',
    },
    {
      code: '072',
      phone: '0267',
      iso: 'BW',
      iso3: 'BWA',
      name: 'Botswana',
      formalName: 'Republic of Botswana',
    },
    {
      code: '074',
      phone: '0047',
      iso: 'BV',
      iso3: 'BVT',
      name: 'Bouvet Island',
      formalName: 'Bouvet Island',
    },
    {
      code: '076',
      phone: '0055',
      iso: 'BR',
      iso3: 'BRA',
      name: 'Brazil',
      formalName: 'Federative Republic of Brazil',
    },
    {
      code: '086',
      phone: '0246',
      iso: 'IO',
      iso3: 'IOT',
      name: 'British Indian Ocean Territory',
      formalName: 'British Indian Ocean Territory',
    },
    {
      code: '096',
      phone: '0673',
      iso: 'BN',
      iso3: 'BRN',
      name: 'Brunei',
      formalName: 'State of Brunei Darussalam',
    },
    {
      code: '100',
      phone: '0359',
      iso: 'BG',
      iso3: 'BGR',
      name: 'Bulgaria',
      formalName: 'Republic of Bulgaria',
    },
    {
      code: '854',
      phone: '0226',
      iso: 'BF',
      iso3: 'BFA',
      name: 'Burkina Faso',
      formalName: 'Burkina Faso',
    },
    {
      code: '108',
      phone: '0257',
      iso: 'BI',
      iso3: 'BDI',
      name: 'Burundi',
      formalName: 'Republic of Burundi',
    },
    {
      code: '116',
      phone: '0855',
      iso: 'KH',
      iso3: 'KHM',
      name: 'Cambodia',
      formalName: 'Kingdom of Cambodia',
    },
    {
      code: '120',
      phone: '0237',
      iso: 'CM',
      iso3: 'CMR',
      name: 'Cameroon',
      formalName: 'Republic of Cameroon',
    },
    {
      code: '124',
      phone: '0001',
      iso: 'CA',
      iso3: 'CAN',
      name: 'Canada',
      formalName: 'Canada',
    },
    {
      code: '132',
      phone: '0238',
      iso: 'CV',
      iso3: 'CPV',
      name: 'Cape Verde',
      formalName: 'Republic of Cape Verde',
    },
    {
      code: '136',
      phone: '1345',
      iso: 'KY',
      iso3: 'CYM',
      name: 'Cayman Islands',
      formalName: 'Cayman Islands',
    },
    {
      code: '140',
      phone: '0236',
      iso: 'CF',
      iso3: 'CAF',
      name: 'Central African Republic',
      formalName: 'Central African Republic',
    },
    {
      code: '148',
      phone: '0235',
      iso: 'TD',
      iso3: 'TCD',
      name: 'Chad',
      formalName: 'Republic of Chad',
    },
    {
      code: '152',
      phone: '0056',
      iso: 'CL',
      iso3: 'CHL',
      name: 'Chile',
      formalName: 'Republic of Chile',
    },
    {
      code: '156',
      phone: '0086',
      iso: 'CN',
      iso3: 'CHN',
      name: 'China',
      formalName: "People's Republic of China",
    },
    {
      code: '162',
      phone: '0061',
      iso: 'CX',
      iso3: 'CXR',
      name: 'Christmas Island',
      formalName: 'Territory of Christmas Island',
    },
    {
      code: '166',
      phone: '0672',
      iso: 'CC',
      iso3: 'CCK',
      name: 'Cocos (Keeling) Islands',
      formalName: 'Territory of the Cocos (Keeling) Islands',
    },
    {
      code: '170',
      phone: '0057',
      iso: 'CO',
      iso3: 'COL',
      name: 'Colombia',
      formalName: 'Republic of Colombia',
    },
    {
      code: '174',
      phone: '0269',
      iso: 'KM',
      iso3: 'COM',
      name: 'Comoros',
      formalName: 'Union of the Comoros',
    },
    {
      code: '178',
      phone: '0242',
      iso: 'CG',
      iso3: 'COG',
      name: 'Congo',
      formalName: 'Republic of the Congo',
    },
    {
      code: '180',
      phone: '0242',
      iso: 'CD',
      iso3: 'COD',
      name: 'Congo (DR)',
      formalName: 'Democratic Republic of the Congo',
    },
    {
      code: '184',
      phone: '0682',
      iso: 'CK',
      iso3: 'COK',
      name: 'Cook Islands',
      formalName: 'Cook Islands',
    },
    {
      code: '188',
      phone: '0506',
      iso: 'CR',
      iso3: 'CRI',
      name: 'Costa Rica',
      formalName: 'Republic of Costa Rica',
    },
    {
      code: '384',
      phone: '0225',
      iso: 'CI',
      iso3: 'CIV',
      name: 'Ivory Coast',
      formalName: 'Republic of Ivory Coast',
    },
    {
      code: '191',
      phone: '0385',
      iso: 'HR',
      iso3: 'HRV',
      name: 'Croatia',
      formalName: 'Republic of Croatia',
    },
    {
      code: '192',
      phone: '0053',
      iso: 'CU',
      iso3: 'CUB',
      name: 'Cuba',
      formalName: 'Republic of Cuba',
    },
    {
      code: '196',
      phone: '0357',
      iso: 'CY',
      iso3: 'CYP',
      name: 'Cyprus',
      formalName: 'Republic of Cyprus',
    },
    {
      code: '203',
      phone: '0420',
      iso: 'CZ',
      iso3: 'CZE',
      name: 'Czech Republic',
      formalName: 'Czech Republic',
    },
    {
      code: '208',
      phone: '0045',
      iso: 'DK',
      iso3: 'DNK',
      name: 'Denmark',
      formalName: 'Kingdom of Denmark',
    },
    {
      code: '262',
      phone: '0253',
      iso: 'DJ',
      iso3: 'DJI',
      name: 'Djibouti',
      formalName: 'Republic of Djibouti',
    },
    {
      code: '212',
      phone: '1767',
      iso: 'DM',
      iso3: 'DMA',
      name: 'Dominica',
      formalName: 'Commonwealth of Dominica',
    },
    {
      code: '214',
      phone: '1809',
      iso: 'DO',
      iso3: 'DOM',
      name: 'Dominican Republic',
      formalName: 'Dominican Republic',
    },
    {
      code: '218',
      phone: '0593',
      iso: 'EC',
      iso3: 'ECU',
      name: 'Ecuador',
      formalName: 'Republic of Ecuador',
    },
    {
      code: '818',
      phone: '0020',
      iso: 'EG',
      iso3: 'EGY',
      name: 'Egypt',
      formalName: 'Arab Republic of Egypt',
    },
    {
      code: '222',
      phone: '0503',
      iso: 'SV',
      iso3: 'SLV',
      name: 'El Salvador',
      formalName: 'Republic of El Salvador',
    },
    {
      code: '226',
      phone: '0240',
      iso: 'GQ',
      iso3: 'GNQ',
      name: 'Equatorial Guinea',
      formalName: 'Republic of Equatorial Guinea',
    },
    {
      code: '232',
      phone: '0291',
      iso: 'ER',
      iso3: 'ERI',
      name: 'Eritrea',
      formalName: 'State of Eritrea',
    },
    {
      code: '233',
      phone: '0372',
      iso: 'EE',
      iso3: 'EST',
      name: 'Estonia',
      formalName: 'Republic of Estonia',
    },
    {
      code: '231',
      phone: '0251',
      iso: 'ET',
      iso3: 'ETH',
      name: 'Ethiopia',
      formalName: 'Federal Democratic Republic of Ethiopia',
    },
    {
      code: '364',
      phone: '0098',
      iso: 'IR',
      iso3: 'IRN',
      name: 'Iran',
      formalName: 'Islamic Republic of Iran',
    },
    {
      code: '368',
      phone: '0964',
      iso: 'IQ',
      iso3: 'IRQ',
      name: 'Iraq',
      formalName: 'Republic of Iraq',
    },
    {
      code: '372',
      phone: '0353',
      iso: 'IE',
      iso3: 'IRL',
      name: 'Ireland',
      formalName: 'Ireland',
    },
    {
      code: '376',
      phone: '0972',
      iso: 'IL',
      iso3: 'ISR',
      name: 'Israel',
      formalName: 'State of Israel',
    },
    {
      code: '380',
      phone: '0039',
      iso: 'IT',
      iso3: 'ITA',
      name: 'Italy',
      formalName: 'Italian Republic',
    },
    {
      code: '388',
      phone: '1876',
      iso: 'JM',
      iso3: 'JAM',
      name: 'Jamaica',
      formalName: 'Jamaica',
    },
    {
      code: '392',
      phone: '0081',
      iso: 'JP',
      iso3: 'JPN',
      name: 'Japan',
      formalName: 'Japan',
    },
    {
      code: '400',
      phone: '0962',
      iso: 'JO',
      iso3: 'JOR',
      name: 'Jordan',
      formalName: 'Hashemite Kingdom of Jordan',
    },
    {
      code: '398',
      phone: '0007',
      iso: 'KZ',
      iso3: 'KAZ',
      name: 'Kazakhstan',
      formalName: 'Republic of Kazakhstan',
    },
    {
      code: '404',
      phone: '0254',
      iso: 'KE',
      iso3: 'KEN',
      name: 'Kenya',
      formalName: 'Republic of Kenya',
    },
    {
      code: '296',
      phone: '0686',
      iso: 'KI',
      iso3: 'KIR',
      name: 'Kiribati',
      formalName: 'Republic of Kiribati',
    },
    {
      code: '408',
      phone: '0850',
      iso: 'KP',
      iso3: 'PRK',
      name: 'North Korea',
      formalName: "Democratic People's Republic of Korea",
    },
    {
      code: '410',
      phone: '0082',
      iso: 'KR',
      iso3: 'KOR',
      name: 'South Korea',
      formalName: 'Republic of Korea',
    },
    {
      code: '414',
      phone: '0965',
      iso: 'KW',
      iso3: 'KWT',
      name: 'Kuwait',
      formalName: 'State of Kuwait',
    },
    {
      code: '417',
      phone: '0996',
      iso: 'KG',
      iso3: 'KGZ',
      name: 'Kyrgyzstan',
      formalName: 'Kyrgyz Republic',
    },
    {
      code: '418',
      phone: '0856',
      iso: 'LA',
      iso3: 'LAO',
      name: 'Laos',
      formalName: "Lao People's Democratic Republic",
    },
    {
      code: '428',
      phone: '0371',
      iso: 'LV',
      iso3: 'LVA',
      name: 'Latvia',
      formalName: 'Republic of Latvia',
    },
    {
      code: '422',
      phone: '0961',
      iso: 'LB',
      iso3: 'LBN',
      name: 'Lebanon',
      formalName: 'Lebanese Republic',
    },
    {
      code: '426',
      phone: '0266',
      iso: 'LS',
      iso3: 'LSO',
      name: 'Lesotho',
      formalName: 'Kingdom of Lesotho',
    },
    {
      code: '430',
      phone: '0231',
      iso: 'LR',
      iso3: 'LBR',
      name: 'Liberia',
      formalName: 'Republic of Liberia',
    },
    {
      code: '434',
      phone: '0218',
      iso: 'LY',
      iso3: 'LBY',
      name: 'Libya',
      formalName: 'Libya',
    },
    {
      code: '438',
      phone: '0423',
      iso: 'LI',
      iso3: 'LIE',
      name: 'Liechtenstein',
      formalName: 'Principality of Liechtenstein',
    },
    {
      code: '440',
      phone: '0370',
      iso: 'LT',
      iso3: 'LTU',
      name: 'Lithuania',
      formalName: 'Republic of Lithuania',
    },
    {
      code: '442',
      phone: '0352',
      iso: 'LU',
      iso3: 'LUX',
      name: 'Luxembourg',
      formalName: 'Grand Duchy of Luxembourg',
    },
    {
      code: '446',
      phone: '0853',
      iso: 'MO',
      iso3: 'MAC',
      name: 'Macau',
      formalName: 'Macau',
    },
    {
      code: '807',
      phone: '0389',
      iso: 'MK',
      iso3: 'MKD',
      name: 'Macedonia',
      formalName: 'Republic of Macedonia',
    },
    {
      code: '450',
      phone: '0261',
      iso: 'MG',
      iso3: 'MDG',
      name: 'Madagascar',
      formalName: 'Republic of Madagascar',
    },
    {
      code: '454',
      phone: '0265',
      iso: 'MW',
      iso3: 'MWI',
      name: 'Malawi',
      formalName: 'Republic of Malawi',
    },
    {
      code: '458',
      phone: '0060',
      iso: 'MY',
      iso3: 'MYS',
      name: 'Malaysia',
      formalName: 'Malaysia',
    },
    {
      code: '462',
      phone: '0960',
      iso: 'MV',
      iso3: 'MDV',
      name: 'Maldives',
      formalName: 'Republic of Maldives',
    },
    {
      code: '466',
      phone: '0223',
      iso: 'ML',
      iso3: 'MLI',
      name: 'Mali',
      formalName: 'Republic of Mali',
    },
    {
      code: '470',
      phone: '0356',
      iso: 'MT',
      iso3: 'MLT',
      name: 'Malta',
      formalName: 'Republic of Malta',
    },
    {
      code: '584',
      phone: '0692',
      iso: 'MH',
      iso3: 'MHL',
      name: 'Marshall Islands',
      formalName: 'Republic of the Marshall Islands',
    },
    {
      code: '474',
      phone: '0596',
      iso: 'MQ',
      iso3: 'MTQ',
      name: 'Martinique',
      formalName: 'Martinique',
    },
    {
      code: '478',
      phone: '0222',
      iso: 'MR',
      iso3: 'MRT',
      name: 'Mauritania',
      formalName: 'Islamic Republic of Mauritania',
    },
    {
      code: '480',
      phone: '0230',
      iso: 'MU',
      iso3: 'MUS',
      name: 'Mauritius',
      formalName: 'Republic of Mauritius',
    },
    {
      code: '175',
      phone: '0269',
      iso: 'YT',
      iso3: 'MYT',
      name: 'Mayotte',
      formalName: 'Department of Mayotte',
    },
    {
      code: '484',
      phone: '0052',
      iso: 'MX',
      iso3: 'MEX',
      name: 'Mexico',
      formalName: 'United Mexican States',
    },
    {
      code: '583',
      phone: '0691',
      iso: 'FM',
      iso3: 'FSM',
      name: 'Micronesia',
      formalName: 'Federated States of Micronesia',
    },
    {
      code: '498',
      phone: '0373',
      iso: 'MD',
      iso3: 'MDA',
      name: 'Moldova',
      formalName: 'Republic of Moldova',
    },
    {
      code: '492',
      phone: '0377',
      iso: 'MC',
      iso3: 'MCO',
      name: 'Monaco',
      formalName: 'Principality of Monaco',
    },
    {
      code: '496',
      phone: '0976',
      iso: 'MN',
      iso3: 'MNG',
      name: 'Mongolia',
      formalName: 'Mongolia',
    },
    {
      code: '500',
      phone: '1664',
      iso: 'MS',
      iso3: 'MSR',
      name: 'Montserrat',
      formalName: 'Montserrat',
    },
    {
      code: '504',
      phone: '0212',
      iso: 'MA',
      iso3: 'MAR',
      name: 'Morocco',
      formalName: 'Kingdom of Morocco',
    },
    {
      code: '508',
      phone: '0258',
      iso: 'MZ',
      iso3: 'MOZ',
      name: 'Mozambique',
      formalName: 'Republic of Mozambique',
    },
    {
      code: '104',
      phone: '0095',
      iso: 'MM',
      iso3: 'MMR',
      name: 'Burma',
      formalName: 'Republic of the Union of Myanmar',
    },
    {
      code: '516',
      phone: '0264',
      iso: 'NA',
      iso3: 'NAM',
      name: 'Namibia',
      formalName: 'Republic of Namibia',
    },
    {
      code: '520',
      phone: '0674',
      iso: 'NR',
      iso3: 'NRU',
      name: 'Nauru',
      formalName: 'Republic of Nauru',
    },
    {
      code: '524',
      phone: '0977',
      iso: 'NP',
      iso3: 'NPL',
      name: 'Nepal',
      formalName: 'Federal Democratic Republic of Nepal',
    },
    {
      code: '528',
      phone: '0031',
      iso: 'NL',
      iso3: 'NLD',
      name: 'Netherlands',
      formalName: 'Netherlands',
    },
    {
      code: '530',
      phone: '0599',
      iso: 'AN',
      iso3: 'ANT',
      name: 'Netherlands Antilles',
      formalName: 'Netherlands Antilles',
    },
    {
      code: '540',
      phone: '0687',
      iso: 'NC',
      iso3: 'NCL',
      name: 'New Caledonia',
      formalName: 'New Caledonia',
    },
    {
      code: '554',
      phone: '0064',
      iso: 'NZ',
      iso3: 'NZL',
      name: 'New Zealand',
      formalName: 'New Zealand',
    },
    {
      code: '558',
      phone: '0505',
      iso: 'NI',
      iso3: 'NIC',
      name: 'Nicaragua',
      formalName: 'Republic of Nicaragua',
    },
    {
      code: '562',
      phone: '0227',
      iso: 'NE',
      iso3: 'NER',
      name: 'Niger',
      formalName: 'Republic of Niger',
    },
    {
      code: '566',
      phone: '0234',
      iso: 'NG',
      iso3: 'NGA',
      name: 'Nigeria',
      formalName: 'Federal Republic of Nigeria',
    },
    {
      code: '570',
      phone: '0683',
      iso: 'NU',
      iso3: 'NIU',
      name: 'Niue',
      formalName: 'Niue',
    },
    {
      code: '574',
      phone: '0672',
      iso: 'NF',
      iso3: 'NFK',
      name: 'Norfolk Island',
      formalName: 'Territory of Norfolk Island',
    },
    {
      code: '580',
      phone: '1670',
      iso: 'MP',
      iso3: 'MNP',
      name: 'Northern Mariana Islands',
      formalName: 'Commonwealth of the Northern Mariana Islands',
    },
    {
      code: '578',
      phone: '0047',
      iso: 'NO',
      iso3: 'NOR',
      name: 'Norway',
      formalName: 'Kingdom of Norway',
    },
    {
      code: '512',
      phone: '0968',
      iso: 'OM',
      iso3: 'OMN',
      name: 'Oman',
      formalName: 'Sultanate of Oman',
    },
    {
      code: '586',
      phone: '0092',
      iso: 'PK',
      iso3: 'PAK',
      name: 'Pakistan',
      formalName: 'Islamic Republic of Pakistan',
    },
    {
      code: '585',
      phone: '0680',
      iso: 'PW',
      iso3: 'PLW',
      name: 'Palau',
      formalName: 'Republic of Palau',
    },
    {
      code: '275',
      phone: '0970',
      iso: 'PS',
      iso3: 'PSE',
      name: 'Palestine',
      formalName: 'State of Palestine',
    },
    {
      code: '591',
      phone: '0507',
      iso: 'PA',
      iso3: 'PAN',
      name: 'Panama',
      formalName: 'Republic of Panama',
    },
    {
      code: '598',
      phone: '0675',
      iso: 'PG',
      iso3: 'PNG',
      name: 'Papua New Guinea',
      formalName: 'Independent State of Papua New Guinea',
    },
    {
      code: '600',
      phone: '0595',
      iso: 'PY',
      iso3: 'PRY',
      name: 'Paraguay',
      formalName: 'Republic of Paraguay',
    },
    {
      code: '604',
      phone: '0051',
      iso: 'PE',
      iso3: 'PER',
      name: 'Peru',
      formalName: 'Republic of Peru',
    },
    {
      code: '608',
      phone: '0063',
      iso: 'PH',
      iso3: 'PHL',
      name: 'Philippines',
      formalName: 'Republic of the Philippines',
    },

    {
      code: '612',
      phone: '0672',
      iso: 'PN',
      iso3: 'PCN',
      name: 'Pitcairn Islands',
      formalName: 'Pitcairn Islands',
    },
    {
      code: '616',
      phone: '0048',
      iso: 'PL',
      iso3: 'POL',
      name: 'Poland',
      formalName: 'Republic of Poland',
    },
    {
      code: '620',
      phone: '0351',
      iso: 'PT',
      iso3: 'PRT',
      name: 'Portugal',
      formalName: 'Portuguese Republic',
    },
    {
      code: '630',
      phone: '1787',
      iso: 'PR',
      iso3: 'PRI',
      name: 'Puerto Rico',
      formalName: 'Commonwealth of Puerto Rico',
    },
    {
      code: '634',
      phone: '0974',
      iso: 'QA',
      iso3: 'QAT',
      name: 'Qatar',
      formalName: 'State of Qatar',
    },
    {
      code: '638',
      phone: '0262',
      iso: 'RE',
      iso3: 'REU',
      name: 'Reunion',
      formalName: 'Poland',
    },
    {
      code: '642',
      phone: '0040',
      iso: 'RO',
      iso3: 'ROM',
      name: 'Romania',
      formalName: 'Romania',
    },
    {
      code: '643',
      phone: '0070',
      iso: 'RU',
      iso3: 'RUS',
      name: 'Russia',
      formalName: 'Russian Federation',
    },
    {
      code: '646',
      phone: '0250',
      iso: 'RW',
      iso3: 'RWA',
      name: 'Rwanda',
      formalName: 'Republic of Rwanda',
    },
    {
      code: '654',
      phone: '0290',
      iso: 'SH',
      iso3: 'SHN',
      name: 'Saint Helena',
      formalName: 'Saint Helena',
    },
    {
      code: '659',
      phone: '1869',
      iso: 'KN',
      iso3: 'KNA',
      name: 'Saint Kitts',
      formalName: 'Saint Kitts',
    },
    {
      code: '662',
      phone: '1758',
      iso: 'LC',
      iso3: 'LCA',
      name: 'Saint Lucia',
      formalName: 'Saint Lucia',
    },
    {
      code: '666',
      phone: '0508',
      iso: 'PM',
      iso3: 'SPM',
      name: 'Saint Pierre and Miquelon',
      formalName: 'Territorial Collectivity of Saint Pierre and Miquelon',
    },
    {
      code: '670',
      phone: '1784',
      iso: 'VC',
      iso3: 'VCT',
      name: 'Saint Vincent and the Grenadines',
      formalName: 'Saint Vincent and the Grenadines',
    },
    {
      code: '882',
      phone: '0684',
      iso: 'WS',
      iso3: 'WSM',
      name: 'Samoa',
      formalName: 'Independent State of Samoa',
    },
    {
      code: '674',
      phone: '0378',
      iso: 'SM',
      iso3: 'SMR',
      name: 'San Marino',
      formalName: 'Republic of San Marino',
    },
    {
      code: '678',
      phone: '0239',
      iso: 'ST',
      iso3: 'STP',
      name: 'Sao Tome and Principe',
      formalName: 'Democratic Republic of Sao Tome and Principe',
    },
    {
      code: '682',
      phone: '0966',
      iso: 'SA',
      iso3: 'SAU',
      name: 'Saudi Arabia',
      formalName: 'Kingdom of Saudi Arabia',
    },
    {
      code: '686',
      phone: '0221',
      iso: 'SN',
      iso3: 'SEN',
      name: 'Senegal',
      formalName: 'Republic of Senegal',
    },
    {
      code: '688',
      phone: '0381',
      iso: 'CS',
      iso3: 'SRB',
      name: 'Serbia and Montenegro',
      formalName: 'State Union of Serbia and Montenegro',
    },
    {
      code: '690',
      phone: '0248',
      iso: 'SC',
      iso3: 'SYC',
      name: 'Seychelles',
      formalName: 'Republic of Seychelles',
    },
    {
      code: '694',
      phone: '0232',
      iso: 'SL',
      iso3: 'SLE',
      name: 'Sierra Leone',
      formalName: 'Republic of Sierra Leone',
    },
    {
      code: '702',
      phone: '0065',
      iso: 'SG',
      iso3: 'SGP',
      name: 'Singapore',
      formalName: 'Republic of Singapore',
    },
    {
      code: '703',
      phone: '0421',
      iso: 'SK',
      iso3: 'SVK',
      name: 'Slovakia',
      formalName: 'Slovak Republic',
    },
    {
      code: '705',
      phone: '0386',
      iso: 'SI',
      iso3: 'SVN',
      name: 'Slovenia',
      formalName: 'Republic of Slovenia',
    },
    {
      code: '090',
      phone: '0677',
      iso: 'SB',
      iso3: 'SLB',
      name: 'Solomon Islands',
      formalName: 'Solomon Islands',
    },
    {
      code: '706',
      phone: '0252',
      iso: 'SO',
      iso3: 'SOM',
      name: 'Somalia',
      formalName: 'Republic of Somalia',
    },
    {
      code: '710',
      phone: '0027',
      iso: 'ZA',
      iso3: 'ZAF',
      name: 'South Africa',
      formalName: 'Republic of South Africa',
    },
    {
      code: '239',
      phone: '0500',
      iso: 'GS',
      iso3: 'SGS',
      name: 'South Georgia and the South Sandwich Islands',
      formalName: 'South Georgia and the South Sandwich Islands',
    },
    {
      code: '724',
      phone: '0034',
      iso: 'ES',
      iso3: 'ESP',
      name: 'Spain',
      formalName: 'Kingdom of Spain',
    },
    {
      code: '144',
      phone: '0094',
      iso: 'LK',
      iso3: 'LKA',
      name: 'Sri Lanka',
      formalName: 'Democratic Socialist Republic of Sri Lanka',
    },
    {
      code: '736',
      phone: '0249',
      iso: 'SD',
      iso3: 'SDN',
      name: 'Sudan',
      formalName: 'Republic of Sudan',
    },
    {
      code: '740',
      phone: '0597',
      iso: 'SR',
      iso3: 'SUR',
      name: 'Suriname',
      formalName: 'Republic of Suriname',
    },
    {
      code: '744',
      phone: '0047',
      iso: 'SJ',
      iso3: 'SJM',
      name: 'Svalbard',
      formalName: 'Svalbard',
    },
    {
      code: '748',
      phone: '0268',
      iso: 'SZ',
      iso3: 'SWZ',
      name: 'Swaziland',
      formalName: 'Kingdom of Swaziland',
    },
    {
      code: '752',
      phone: '0046',
      iso: 'SE',
      iso3: 'SWE',
      name: 'Sweden',
      formalName: 'Kingdom of Sweden',
    },
    {
      code: '756',
      phone: '0041',
      iso: 'CH',
      iso3: 'CHE',
      name: 'Switzerland',
      formalName: 'Swiss Confederation',
    },
    {
      code: '760',
      phone: '0963',
      iso: 'SY',
      iso3: 'SYR',
      name: 'Syria',
      formalName: 'Syrian Arab Republic',
    },
    {
      code: '158',
      phone: '0886',
      iso: 'TW',
      iso3: 'TWN',
      name: 'Taiwan',
      formalName: 'Taiwan',
    },
    {
      code: '762',
      phone: '0992',
      iso: 'TJ',
      iso3: 'TJK',
      name: 'Tajikistan',
      formalName: 'Republic of Tajikistan',
    },
    {
      code: '834',
      phone: '0255',
      iso: 'TZ',
      iso3: 'TZA',
      name: 'Tanzania',
      formalName: 'United Republic of Tanzania',
    },
    {
      code: '764',
      phone: '0066',
      iso: 'TH',
      iso3: 'THA',
      name: 'Thailand',
      formalName: 'Kingdom of Thailand',
    },
    {
      code: '626',
      phone: '0670',
      iso: 'TL',
      iso3: 'TLS',
      name: 'Timor-Leste',
      formalName: 'Democratic Republic of Timor-Leste',
    },

    {
      code: '612',
      phone: '0672',
      iso: 'PN',
      iso3: 'PCN',
      name: 'Pitcairn Islands',
      formalName: 'Pitcairn Islands',
    },
    {
      code: '616',
      phone: '0048',
      iso: 'PL',
      iso3: 'POL',
      name: 'Poland',
      formalName: 'Republic of Poland',
    },
    {
      code: '620',
      phone: '0351',
      iso: 'PT',
      iso3: 'PRT',
      name: 'Portugal',
      formalName: 'Portuguese Republic',
    },
    {
      code: '630',
      phone: '1787',
      iso: 'PR',
      iso3: 'PRI',
      name: 'Puerto Rico',
      formalName: 'Commonwealth of Puerto Rico',
    },
    {
      code: '634',
      phone: '0974',
      iso: 'QA',
      iso3: 'QAT',
      name: 'Qatar',
      formalName: 'State of Qatar',
    },
    {
      code: '638',
      phone: '0262',
      iso: 'RE',
      iso3: 'REU',
      name: 'Reunion',
      formalName: 'Poland',
    },
    {
      code: '642',
      phone: '0040',
      iso: 'RO',
      iso3: 'ROM',
      name: 'Romania',
      formalName: 'Romania',
    },
    {
      code: '643',
      phone: '0070',
      iso: 'RU',
      iso3: 'RUS',
      name: 'Russia',
      formalName: 'Russian Federation',
    },
    {
      code: '646',
      phone: '0250',
      iso: 'RW',
      iso3: 'RWA',
      name: 'Rwanda',
      formalName: 'Republic of Rwanda',
    },
    {
      code: '654',
      phone: '0290',
      iso: 'SH',
      iso3: 'SHN',
      name: 'Saint Helena',
      formalName: 'Saint Helena',
    },
    {
      code: '659',
      phone: '1869',
      iso: 'KN',
      iso3: 'KNA',
      name: 'Saint Kitts',
      formalName: 'Saint Kitts',
    },
    {
      code: '662',
      phone: '1758',
      iso: 'LC',
      iso3: 'LCA',
      name: 'Saint Lucia',
      formalName: 'Saint Lucia',
    },
    {
      code: '666',
      phone: '0508',
      iso: 'PM',
      iso3: 'SPM',
      name: 'Saint Pierre and Miquelon',
      formalName: 'Territorial Collectivity of Saint Pierre and Miquelon',
    },
    {
      code: '670',
      phone: '1784',
      iso: 'VC',
      iso3: 'VCT',
      name: 'Saint Vincent and the Grenadines',
      formalName: 'Saint Vincent and the Grenadines',
    },
    {
      code: '882',
      phone: '0684',
      iso: 'WS',
      iso3: 'WSM',
      name: 'Samoa',
      formalName: 'Independent State of Samoa',
    },
    {
      code: '674',
      phone: '0378',
      iso: 'SM',
      iso3: 'SMR',
      name: 'San Marino',
      formalName: 'Republic of San Marino',
    },
    {
      code: '678',
      phone: '0239',
      iso: 'ST',
      iso3: 'STP',
      name: 'Sao Tome and Principe',
      formalName: 'Democratic Republic of Sao Tome and Principe',
    },
    {
      code: '682',
      phone: '0966',
      iso: 'SA',
      iso3: 'SAU',
      name: 'Saudi Arabia',
      formalName: 'Kingdom of Saudi Arabia',
    },
    {
      code: '686',
      phone: '0221',
      iso: 'SN',
      iso3: 'SEN',
      name: 'Senegal',
      formalName: 'Republic of Senegal',
    },
    {
      code: '688',
      phone: '0381',
      iso: 'CS',
      iso3: 'SRB',
      name: 'Serbia and Montenegro',
      formalName: 'State Union of Serbia and Montenegro',
    },
    {
      code: '690',
      phone: '0248',
      iso: 'SC',
      iso3: 'SYC',
      name: 'Seychelles',
      formalName: 'Republic of Seychelles',
    },
    {
      code: '694',
      phone: '0232',
      iso: 'SL',
      iso3: 'SLE',
      name: 'Sierra Leone',
      formalName: 'Republic of Sierra Leone',
    },
    {
      code: '702',
      phone: '0065',
      iso: 'SG',
      iso3: 'SGP',
      name: 'Singapore',
      formalName: 'Republic of Singapore',
    },
    {
      code: '703',
      phone: '0421',
      iso: 'SK',
      iso3: 'SVK',
      name: 'Slovakia',
      formalName: 'Slovak Republic',
    },
    {
      code: '705',
      phone: '0386',
      iso: 'SI',
      iso3: 'SVN',
      name: 'Slovenia',
      formalName: 'Republic of Slovenia',
    },
    {
      code: '090',
      phone: '0677',
      iso: 'SB',
      iso3: 'SLB',
      name: 'Solomon Islands',
      formalName: 'Solomon Islands',
    },
    {
      code: '706',
      phone: '0252',
      iso: 'SO',
      iso3: 'SOM',
      name: 'Somalia',
      formalName: 'Republic of Somalia',
    },
    {
      code: '710',
      phone: '0027',
      iso: 'ZA',
      iso3: 'ZAF',
      name: 'South Africa',
      formalName: 'Republic of South Africa',
    },
    {
      code: '239',
      phone: '0500',
      iso: 'GS',
      iso3: 'SGS',
      name: 'South Georgia and the South Sandwich Islands',
      formalName: 'South Georgia and the South Sandwich Islands',
    },
    {
      code: '724',
      phone: '0034',
      iso: 'ES',
      iso3: 'ESP',
      name: 'Spain',
      formalName: 'Kingdom of Spain',
    },
    {
      code: '144',
      phone: '0094',
      iso: 'LK',
      iso3: 'LKA',
      name: 'Sri Lanka',
      formalName: 'Democratic Socialist Republic of Sri Lanka',
    },
    {
      code: '736',
      phone: '0249',
      iso: 'SD',
      iso3: 'SDN',
      name: 'Sudan',
      formalName: 'Republic of Sudan',
    },
    {
      code: '740',
      phone: '0597',
      iso: 'SR',
      iso3: 'SUR',
      name: 'Suriname',
      formalName: 'Republic of Suriname',
    },
    {
      code: '744',
      phone: '0047',
      iso: 'SJ',
      iso3: 'SJM',
      name: 'Svalbard',
      formalName: 'Svalbard',
    },
    {
      code: '748',
      phone: '0268',
      iso: 'SZ',
      iso3: 'SWZ',
      name: 'Swaziland',
      formalName: 'Kingdom of Swaziland',
    },
    {
      code: '752',
      phone: '0046',
      iso: 'SE',
      iso3: 'SWE',
      name: 'Sweden',
      formalName: 'Kingdom of Sweden',
    },
    {
      code: '756',
      phone: '0041',
      iso: 'CH',
      iso3: 'CHE',
      name: 'Switzerland',
      formalName: 'Swiss Confederation',
    },
    {
      code: '760',
      phone: '0963',
      iso: 'SY',
      iso3: 'SYR',
      name: 'Syria',
      formalName: 'Syrian Arab Republic',
    },
    {
      code: '158',
      phone: '0886',
      iso: 'TW',
      iso3: 'TWN',
      name: 'Taiwan',
      formalName: 'Taiwan',
    },
    {
      code: '762',
      phone: '0992',
      iso: 'TJ',
      iso3: 'TJK',
      name: 'Tajikistan',
      formalName: 'Republic of Tajikistan',
    },
    {
      code: '834',
      phone: '0255',
      iso: 'TZ',
      iso3: 'TZA',
      name: 'Tanzania',
      formalName: 'United Republic of Tanzania',
    },
    {
      code: '764',
      phone: '0066',
      iso: 'TH',
      iso3: 'THA',
      name: 'Thailand',
      formalName: 'Kingdom of Thailand',
    },
    {
      code: '626',
      phone: '0670',
      iso: 'TL',
      iso3: 'TLS',
      name: 'Timor-Leste',
      formalName: 'Democratic Republic of Timor-Leste',
    },

    {
      code: '768',
      phone: '0228',
      iso: 'TG',
      iso3: 'TGO',
      name: 'Togo',
      formalName: 'Togolese Republic',
    },
    {
      code: '776',
      phone: '0676',
      iso: 'TO',
      iso3: 'TON',
      name: 'Tonga',
      formalName: 'Kingdom of Tonga',
    },
    {
      code: '780',
      phone: '1868',
      iso: 'TT',
      iso3: 'TTO',
      name: 'Trinidad and Tobago',
      formalName: 'Republic of Trinidad and Tobago',
    },
    {
      code: '788',
      phone: '0216',
      iso: 'TN',
      iso3: 'TUN',
      name: 'Tunisia',
      formalName: 'Tunisian Republic',
    },
    {
      code: '792',
      phone: '0090',
      iso: 'TR',
      iso3: 'TUR',
      name: 'Turkey',
      formalName: 'Republic of Turkey',
    },
    {
      code: '795',
      phone: '0993',
      iso: 'TM',
      iso3: 'TKM',
      name: 'Turkmenistan',
      formalName: 'Turkmenistan',
    },
    {
      code: '796',
      phone: '0164',
      iso: 'TC',
      iso3: 'TCA',
      name: 'Turks and Caicos Islands',
      formalName: 'Turks and Caicos Islands',
    },
    {
      code: '798',
      phone: '0688',
      iso: 'TV',
      iso3: 'TUV',
      name: 'Tuvalu',
      formalName: 'Tuvalu',
    },
    {
      code: '800',
      phone: '0256',
      iso: 'UG',
      iso3: 'UGA',
      name: 'Uganda',
      formalName: 'Republic of Uganda',
    },
    {
      code: '804',
      phone: '0380',
      iso: 'UA',
      iso3: 'UKR',
      name: 'Ukraine',
      formalName: 'Ukraine',
    },
    {
      code: '784',
      phone: '0971',
      iso: 'AE',
      iso3: 'ARE',
      name: 'United Arab Emirates',
      formalName: 'United Arab Emirates',
    },
    {
      code: '826',
      phone: '0044',
      iso: 'GB',
      iso3: 'GBR',
      name: 'United Kingdom',
      formalName: 'United Kingdom of Great Britain and Northern Ireland',
    },
    {
      code: '840',
      phone: '0001',
      iso: 'US',
      iso3: 'USA',
      name: 'United States',
      formalName: 'United States of America',
    },
    {
      code: '858',
      phone: '0598',
      iso: 'UY',
      iso3: 'URY',
      name: 'Uruguay',
      formalName: 'Eastern Republic of Uruguay',
    },
    {
      code: '860',
      phone: '0998',
      iso: 'UZ',
      iso3: 'UZB',
      name: 'Uzbekistan',
      formalName: 'Republic of Uzbekistan',
    },
    {
      code: '548',
      phone: '0678',
      iso: 'VU',
      iso3: 'VUT',
      name: 'Vanuatu',
      formalName: 'Republic of Vanuatu',
    },
    {
      code: '862',
      phone: '0058',
      iso: 'VE',
      iso3: 'VEN',
      name: 'Venezuela',
      formalName: 'Bolivarian Republic of Venezuela',
    },
    {
      code: '704',
      phone: '0084',
      iso: 'VN',
      iso3: 'VNM',
      name: 'Vietnam',
      formalName: 'Socialist Republic of Vietnam',
    },
    {
      code: '876',
      phone: '0681',
      iso: 'WF',
      iso3: 'WLF',
      name: 'Wallis and Futuna',
      formalName: 'Wallis and Futuna',
    },
    {
      code: '732',
      phone: '0212',
      iso: 'EH',
      iso3: 'ESH',
      name: 'Western Sahara',
      formalName: 'Sahrawi Arab Democratic Republic',
    },
    {
      code: '887',
      phone: '0967',
      iso: 'YE',
      iso3: 'YEM',
      name: 'Yemen',
      formalName: 'Republic of Yemen',
    },
    {
      code: '894',
      phone: '0260',
      iso: 'ZM',
      iso3: 'ZMB',
      name: 'Zambia',
      formalName: 'Republic of Zambia',
    },
    {
      code: '716',
      phone: '0263',
      iso: 'ZW',
      iso3: 'ZWE',
      name: 'Zimbabwe',
      formalName: 'Republic of Zimbabwe',
    },
  ]);
}
